## Exception Handling.

*throw* Statement is for  throwing an exception and it can be caught by a try block in the code.

```js
try{

}
catch (exception){
  console.error()
}
finally{

}
```


When logging errors to the console inside a catch block, using console.error() rather than console.log() is advised for debugging. It formats the message as an error, and adds it to the list of error messages generated by the page.


*finally* block will execute whether or not an exception is thrown.
We use this to make your script fail gracefully

# Few Point to remember

- If the finally block returns a value, this value becomes the return value of the entire try…catch…finally production, regardless of any return statements in the try and catch blocks

- Overwriting of return values by the finally block also applies to exceptions thrown or re-thrown inside of the catch block